version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: build
    command: go run src/main.go
    tty: true
    stdin_open: true
    volumes:
    - .:/go/github-gantt-api
    ports:
    - 5000:5000
    env_file:
      - .env